// Code generated by "stringer -type Token"; DO NOT EDIT.

package lisp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invalid-0]
	_ = x[Id-1]
	_ = x[Number-2]
	_ = x[LParen-3]
	_ = x[RParen-4]
	_ = x[Pre-5]
	_ = x[Code-6]
}

const _Token_name = "InvalidIdNumberLParenRParenPreCode"

var _Token_index = [...]uint8{0, 7, 9, 15, 21, 27, 30, 34}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
